version: '3'

services:
  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./Corrected_Marks_vs_Rank.xlsx:/app/Corrected_Marks_vs_Rank.xlsx
      - ./cleaned_data:/app/cleaned_data
    environment:
      - TZ=Asia/Kolkata
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app 