service: neet-rank-predictor

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1
  timeout: 30  # Increase the Lambda timeout to 30 seconds
  memorySize: 512  # Increase memory to improve performance
  
functions:
  app:
    handler: main.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
    environment:
      PYTHONPATH: .
    package:
      include:
        - main.py
        - Corrected_Marks_vs_Rank.xlsx
        - cleaned_data/**
    timeout: 30  # Function-specific timeout
    memorySize: 512  # Function-specific memory
    reservedConcurrency: 5  # Limit concurrency to prevent throttling

custom:
  pythonRequirements:
    slim: true  # Reduce package size

plugins:
  - serverless-python-requirements 